### PR TITLE
Enable compatibility to iojs 1.4.3 et al.; update to libssh-0.6.4, nan 1.7.0

### PR DESCRIPTION
**Pull request by 19h**
Hey Rodd,

I know this is an extreme anti-pattern, but since nothing happened in the other open PRs, I implicitly merged them with my PR here.

Overview:
- Pull in the PR by @dirk allowing compilation on OS X Yosemite (_Thanks, @dirk!_)
- Pull in the PR by @deian which migrated the _ancient nan_ to _nan 1.3.0_. (_Thanks, @deian!_)
- **sftp_message.cc**: Migrate `NanNew<v8::Integer>(int64)` to `NanNew<v8::Number>(int64)`, because v8::Integer doesn't implicitly recasts the int64 anymore.

I tested this with iojs 1.4.3 and node 0.12.0.

Cheers!

### CODE REVIEW

**Comment by dirk** [comment]
This looks great. I have my own little branch locally with libssh-0.6.4 and a really recent nan, but couldn't get some of the tests to pass for weird reasons. Delighted to see you managed to get it working, @KenanSulayman!

*Light tap on the shoulder to @rvagg to see if he could merge this puppy.*

**Comment by rvagg** [comment]
thanks @KenanSulayman, a priority for me is to hand off responsibility for this project, I don't use it enough for it to be important--it's more important to other people so it needs to be cared for more than I can afford to atm

**Comment by KenanSulayman** [comment]
I should mention that I found out about this project less than 24 hours ago at lunch and updated it, because it didn't compile. That is, I am not intimately familiar with all of the source code. But as far as my 9to5 goes, I wouldn't hurt me to maintain this. :beer:

**Comment by dirk** [comment]
Been using the SFTP part of this for a while now, so I've got some personal technical investment and would be more than happy to help you out with maintaining, @KenanSulayman.

**Comment by dirk** [comment]
So, @rvagg, do you want to hand off to @KenanSulayman?

**Comment by rvagg** [comment]
@dariusc93
@alessioalex
@mscdex
@AudriusButkevicius
@maboiteaspam
@R4wizard
@jamesallen426
@deian
@jawsome

You are all collaborators here, are any of you invested in the module enough to take over release responsibility?

My proposal is to add both @KenanSulayman and @dirk to the collaborators list and give @KenanSulayman `npm publish` access but I'd love to hear from any existing collaborators who think they are in a position to take some of this responsibility. Ideally someone needs to be actually using this so that the responsibility for ensuring quality releases weighs heavily. I'm not in this position right now so it's best if I offload it, particularly because I've become so busy elsewhere.

**Comment by AudriusButkevicius** [comment]
I only used this as a prototype, and haven't used it for a while, so feel free to do as you may.

**Comment by dirk** [comment]
My consulting [firm](http://development.bycoast.com/) is using it actively to enable some fancy server interactions for our clients, so I think I can say I have some "skin in the game". :wink: With that in mind I'm willing to keep up with watching for quality and stability in bugfixes and releases.

**Comment by mscdex** [comment]
I had mainly been using this as an alternative to spinning up OpenSSH servers for testing purposes until [`ssh2`](https://github.com/mscdex/ssh2)/[`ssh2-streams`](https://github.com/mscdex/ssh2-streams) had a pure js server implementation, which they now have. I've also been increasingly busy with other projects so I haven't had time to devote to this module unfortunately.

It sounds like @dirk and @KenanSulayman are in a better position to be maintaining this repo than I.

**Comment by KenanSulayman** [comment]
Any update on this? I'd still be happy to coin in. :racehorse:

**Comment by R4wizard** [comment]
@rvagg I'm currently not using the project anymore. I was never able to get SFTP support working as I hoped. I too have become quite busy elsewhere at the moment. I'll still be keeping an eye on this though!

**Comment by rvagg** [comment]
I've added @KenanSulayman as a maintainer and as having publish rights on npm, sorry for the delay here all! @KenanSulayman please put yourself on the README, in the package.json and anywhere else appropriate!

**Comment by KenanSulayman** [comment]
Awesome, thanks @rvagg!

I'll kick this off as soon as I leave the office, I hope you guys have that few hours left to spare :-)

Cheers!

**Comment by KenanSulayman** [comment]
Landed: https://github.com/rvagg/node-libssh/commit/efc4cf262bedc51149723c28f23c344a359a1a97 - https://github.com/rvagg/node-libssh/commit/134f8fabe61b2e33fea0aa80bd9fe00b7344c385.

**Comment by 19h** [comment]
Published as **1.8.0**.

**Pull request merged**
